# Download obsidian AppImage
- name: Download Obsidian 1.1.16 AppImage
  ansible.builtin.get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.1.16/Obsidian-1.1.16.AppImage"
    dest: "/home/{{ username }}/Software/Obsidian-1.1.16.AppImage"
    mode: 0775

# Make obsidian executable
- name: Make Obdisian 1.1.16 AppImage executable
  ansible.builtin.file:
    path: "/home/{{ username }}/Software/Obsidian-1.1.16.AppImage"
    mode: 0775
    owner: "{{ username }}"
    group: "{{ username }}"


